### ISSUE TITLE
Some of the most concerning issues

### ISSUE THREAD

**Issue by Johuo** [1d51/mv-mod-loader#11]
1.Will MZ be supported in the future?
2. Is there a quick test sample? It is easy to quickly know whether it is working properly.
3.Backing up raw files doesn't include backing up assets like images, right? Can the mod be manually set to use the pictures in the original file directly?

**Comment by 1d51** [comment]
1. I have no plans to officially support it.
2. Not really, but making one should be simple enough.
3. It does back up assets and restores them once the mod is disabled. Don't understand the second question though.

**Comment by Johuo** [comment]
I've already used it for mz (not fully functionally tested yet) and recommend you support it quickly as it's very simple.
1. Compared with MV, MZ does not have a WWW folder in the root directory after the game is packaged.
2. The bug mainly comes from the method of building the mod list, which fails in MZ, and the text window prompting to restart after opening the mod.

**Comment by 1d51** [comment]
If you've made the changes to make it work, would you mind opening a PR, or sending me the modified files, once tested? I'd be more than happy to have the mod loader support MZ officially, and you'd be credited of course.

**Comment by Johuo** [comment]
https://drive.google.com/file/d/1-2EQRLLBSJjDfKR8Xu3z5jllWMNNpSuX/view?usp=drive_link
I have not modified any code snippets about "WWW" My way to bypass this problem and test directly is to use MV to deploy the MZ project.
Compared to mv,in MZ's system. json, the screen resolution parameter is added.This is the change in the data structure updated by the rm publisher for mz.This is just my insignificant reminder.
What I mainly want to know now is whether support for mz has been included in the plan?

**Comment by 1d51** [comment]
> https://drive.google.com/file/d/1-2EQRLLBSJjDfKR8Xu3z5jllWMNNpSuX/view?usp=drive_link I have not modified any code snippets about "WWW" My way to bypass this problem and test directly is to use MV to deploy the MZ project. Compared to mv,in MZ's system. json, the screen resolution parameter is added.This is the change in the data structure updated by the rm publisher for mz.This is just my insignificant reminder. What I mainly want to know now is whether support for mz has been included in the plan?

Sorry for the late reply, had some things to take care of. Seems simple enough to add support for MZ, so I'll add it to the list of possible improvements. I can't promise a date or anything, but I'll keep it in mind.

**Comment by Johuo** [comment]
I noticed that your original intention was to write a MOD framework for the nfsw game, and I noticed another interesting plug-in that allows the game to have chapter selections, which means that with your framework, modders can create new adventures.
MZ:https://github.com/snailbaron/rpg-maker-plugins/blob/main/SNBR_CustomMenu.js
MV:https://ltngames.itch.io/fenixenginemv-chapter-select
I didn't test the chapter selection for the MV.
