### ISSUE TITLE
Are you intentionally incompatible with mz

### ISSUE THREAD

**Issue by Johuo** [1d51/mv-mod-loader#18]
In version 2.4.6, I fixed the window class bug that only existed in mz.
I originally thought that if I designed a compatibility patch, I could bring your updates to MZ as soon as possible.
But the next version number jumps directly to 2.50, and you immediately switch to a new method of generating bugs.
Yesterday I checked the latest version, and the error message was as follows: at Window_Mods.Window_Base.checkRectObject (rmmz_windows.js:42).
I found the script here: Window_Base.prototype.checkRectObject = function(rect) {
     if (typeof rect !== "object" || !("x" in rect)) {
         // Probably MV plugin is used
         throw new Error("Argument must be a Rectangle");
     }
};

**Comment by 1d51** [comment]
Yes I just have a general hatred for MZ. If you have some changes you'd like to see included in the plugin, please open a PR.
