### ISSUE TITLE
Game not fully closing when enabling a mod

### ISSUE THREAD

**Issue by TheRealFame** [1d51/mv-mod-loader#4]
I love this plugin! it does what i want it to, and makes it so people can load mods via the game itself, one issue though- is that when applying the mod, it then locks the game up and waits for the player to reset it, instead of just closing the game so the player knows to reopn it, it may just be because a improper line of code is in the plugin itself. but that doesnt mean the issue isnt there. 😅

**Comment by 1d51** [comment]
Glad you like it! The game should close when applying the mod. At the very least it does in the game I'm using it at. I've added another call to try and make sure it closes. Let me know how it goes!

https://github.com/1d51/mv-mod-loader/archive/refs/heads/main.zip

**Comment by TheRealFame** [comment]
ahh, tried it with the new version! now it just straight up crashes when leaving mods- so as soon as they press back it locks up and freezes in place showing that the mod was selected, but they just can't do anything. Also! it may be because you are not using the same script call my exit plugin uses, (process.exit();) that should be the default way to close the nwjs browser- atleast for me.
also! while im here, i may as well suggest you look at the site https://mods.io to see if you could make this mod loader working with it! that could help most people out in the rpg maker community submit their mods via a third party site instead of asking the dev...

**Comment by 1d51** [comment]
What plugin is that, do you have a link? AFAIK the default way to close the game is with either of the function calls I'm making. About integrating with mods.io, it's not planned, but who knows, might happen in the future.

**Comment by TheRealFame** [comment]
Hmmm I see for the second comment.. but no plugin- I had to modify a plugin. Since it kept calling for a different way to close the game but it just kept freezing instead of actually closing the game, I believe it's the native way to close node.js or nwjs.

**Comment by 1d51** [comment]
I assume modifying this plugin makes it work for your case? If you haven't tried it, it's this line:
https://github.com/1d51/mv-mod-loader/blob/main/www/js/plugins/1d51ModLoader.js#L735

Do you have any docs that mention the use of process.exit() in RPG Maker MV? I'd rather hold off from making that change until I'm sure it won't be a problem for other games.

**Comment by TheRealFame** [comment]
Thanks for telling me what line it is! Also no- I don't know if it mentions that function, but for me all plugins that adds a exit button didn't work because it used a different function- it probably worked when the engine first released though. If I had to guess. Just not now-

**Comment by TheRealFame** [comment]
Yup, changing the line to what i normally used fixed it for me- i do not see how others have zero issues with the window close command instead of process close, but of course- since the issue is fixed. no need for me to keep this open.. ill still recommend making a alt version of this plugin for people who have the same issue as me and do not know it!

**Comment by 1d51** [comment]
I think I'll keep this issue open for that actually, if someone has this same problem, they'll be able to find the solution.

**Comment by TheRealFame** [comment]
Oh, alright

**Comment by 1d51** [comment]
With the latest release, the mod loader now restarts the game on its own. Hopefully this is no longer an issue :)

**Comment by TheRealFame** [comment]
Oooh! I'll go ahead and test that;

**Comment by TheRealFame** [comment]
It actually restarted! seems you may of just refreshed the game entirely with a function or such
