### ISSUE TITLE
Forgot to ask, not a issue. But a question.

### ISSUE THREAD

**Issue by TheRealFame** [1d51/mv-mod-loader#5]
Is mobile mod support gonna come to this plugin? Or is it not possible?

**Comment by TheRealFame** [comment]
And will there be a way to implement a "mod page" with all the listed activated and deactivated mods that take the player onto wherever site is listed as the games mod page, so they can install mods from there?

**Comment by 1d51** [comment]
Mobile support would require a big rework I think, but the core should be portable? Not sure. I have thought of ways of adding a more seamless mod download and installation. I might add something along that line in the future.

**Comment by TheRealFame** [comment]
Ahh, alright!

**Comment by TheRealFame** [comment]
Hmmm, any plans for a mods page update to add a redirect for the player to have a website opened in their browser showing mods for the game that they can download

**Comment by 1d51** [comment]
I have thought about it, but haven't had the time. So maybe.

**Comment by TheRealFame** [comment]
Hmmm, well hopefully it's simple, I was just thinking of allowing free name of what it's called, what the url opens, and if it should be used

**Comment by TheRealFame** [comment]
Hmmm, Another question cause this idea sounds neat to me. Do zip files work? I could try using them, and making my own file extention. Like something called "CFMod" Just so people know what game the mod/file is associated to.

**Comment by 1d51** [comment]
Right now they don't, but it's doable. Development of this plugin is kinda frozen on my end for now though. So other than fixes, I doubt I'll be adding new features any time soon.

**Comment by TheRealFame** [comment]
> Right now they don't, but it's doable. Development of this plugin is kinda frozen on my end for now though. So other than fixes, I doubt I'll be adding new features any time soon.

Oh- hmmm.. then I hope everything is well as well, on your end..

**Comment by TheRealFame** [comment]
> And will there be a way to implement a "mod page" with all the listed activated and deactivated mods that take the player onto wherever site is listed as the games mod page, so they can install mods from there?

Is it time we think about this again? 👀, I feel you can just take the code of a redirect plugin and implement it for a button in the mod's menu

**Comment by 1d51** [comment]
Not a priority for me right now, but I'm open to pull requests!
