### ISSUE TITLE
Am i uh- am i doing this right?

### ISSUE THREAD

**Issue by TheRealFame** [1d51/mv-mod-loader#6]
[metadata.txt](https://github.com/1d51/mv-mod-loader/files/11337230/metadata.txt)

**Comment by TheRealFame** [comment]
Also, sorry for opening all these issues! you can still close them after they are fixed, i like to make multiple issues just for closing one or for deleting unnecessary info, but keep info others may find helpful available to view

**Comment by TheRealFame** [comment]
but the main issue of this is i dont know how to add multiple mods to the incompatible section in the mods metadata

**Comment by 1d51** [comment]
No worries, these will be useful for others! Here's a working example of `metadata.json` (`metadata.txt` might now work).
```
 {
	"name": "Example",
	"version": "0.0.1",
	"dependencies": [],
	"incompatible": [
		{
			"name": "First"
		},
		{
			"name": "Second"
		}
	],
	"overrides": {}
}
```

**Comment by TheRealFame** [comment]
Oh! Thanks, I'll go ahead and try it!
