### ISSUE TITLE
Consider dependencies when reducing mods

### ISSUE THREAD

**Issue by 1d51** [1d51/mv-mod-loader#8]
When a mod adds a dependency to their `metadata.json`, it's fair to assume it makes changes on top of those by the dependency, and so it can probably be reduced more accurately if we compare it to said dependency, rather than the base game.

**Comment by TheRealFame** [comment]
👀 more work on the plugin it seems

**Comment by 1d51** [comment]
Minor stuff but yeah, I basically update it when a modder finds an issue with it.

**Comment by TheRealFame** [comment]
> Minor stuff but yeah, I basically update it when a modder finds an issue with it.

Oh! In that case I'll grab the new version after I check it's code out
